package:
  name: httpbin
  version: "0.6.2"

source:
  fn: httpbin-0.6.2.tar.gz
  url: https://pypi.python.org/packages/63/01/5ed5d0d9a15f855fd82a99713a55ddaae70f8344327e4b2c676cba3494ff/httpbin-0.6.2.tar.gz
  md5: cade8ea5eaed811ef062a18db2b8e9e9
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch: python
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - httpbin = httpbin:main
    #
    # Would create an entry point called httpbin that calls httpbin.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - flask
    - markupsafe
    - decorator
    - itsdangerous
    - six
    - brotlipy
    - raven[flask]
    - flask_limiter
    - flask-common

  run:
    - python
    - flask
    - markupsafe
    - decorator
    - itsdangerous
    - six
    - brotlipy
    - raven[flask]
    - flask_limiter
    - flask-common

test:
  # Python imports
  imports:
    - httpbin

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/kennethreitz/httpbin
  license: MIT License
  summary: 'HTTP Request and Response Service'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
